---
AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb
  Include:
    - '**/*.thor'

Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/*

Style/AccessorMethodName:
  Exclude:
   - demo/spin_api_client.thor

Metrics/ClassLength:
  Exclude:
    - bin/api-ca
    - demo/spin_api_client.thor

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb
