---
- hosts: spin-server
  vars:
    db:
      name: spin
      username: spin_app
    tomcat:
      major: 8
      version: 8.0.15
      sha256sum: 2cc244070d01193c541e526564068e6f4e9ecade22380e38e681e931f3dc3699
      mariadb:
        version: 1.1.7
        sha256sum: ff0b807b9209fbd5e05d62152006f6a43868ba7f55bb9716035dc6d8a5382390
  vars_files:
    - spin.config
  tasks:
    - name: 'Ensure SPIN distribution has been extracted correctly'
      shell: >
        if [ ! -e /opt/spin/app/config/application.rb ]; then
          echo
          echo
          echo '*** Please ensure the contents of the SPIN distribution are extracted to /opt/spin ***'
          exit 1
        fi
      changed_when: false

    - name: 'Create service user'
      user:
        name: spin
        home: /opt/spin
        password: '!!'

    - name: 'Create required directories'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: spin
        mode: 0750
      with_items:
        - /opt/spin
        - /opt/spin/app
        - /opt/spin/downloads
        - /opt/spin/tomcat

    # Ensures the generated credentials are not readable by the webapp.
    - name: 'Lock down setup directories'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - /opt/spin/app/setup
        - /opt/spin/app/setup/passwords

    - name: 'Install required packages'
      yum: pkg={{ item }} state=installed
      with_items:
        - ntp
        - mariadb-server
        - mariadb-devel
        - mariadb
        - redis
        - java-1.7.0-openjdk-headless

    - name: 'Enable NTP service'
      service: name=ntpd state=started enabled=yes

    - include: tasks/db.yml
    - include: tasks/redis.yml
    - include: tasks/tomcat.yml
